on:
  push:
    branches:
      - main
name: release-please
jobs:
  package-finder:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Checkout aries-framework-javascript-ext
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - id: get-packages
        name: Get all NPM packages
        run: yarn ts-node ./scripts/getPackages.ts

  release:
    runs-on: ubuntu-latest
    needs:
      - package-finder
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.package-finder.outputs.packages)}}
    steps:
      - uses: google-github-actions/release-please-action@v2
        id: release-please
        with:
          path: packages/${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: ${{ matrix.package }}
          bump-minor-pre-major: true
          monorepo-tags: true

      # Initiate release process if release was created
      - name: Checkout aries-framework-javascript-ext
        uses: actions/checkout@v2
        if: ${{ steps.release-please.outputs.release_created }}
      - name: Setup NodeJS
        uses: ./.github/actions/setup-node
        with:
          node-version: 16
        if: ${{ steps.release-please.outputs.release_created }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - run: |
          cd packages/${{ matrix.package }}
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
